### PR TITLE
Upgrade elixir 1.9 and automate version update process

### PR DESCRIPTION
**Pull request by nicocharlery**

### CODE REVIEW

**Review by nicholasjhenry — CHANGES_REQUESTED** [review]
This looks good, @bokay. The `elixir/README.md` will need to be updated with references to the new make commands.

**Comment by nicholasjhenry** [comment]
@bokay Also this make file is specific to the `elixir` docker image, it should be moved to the `elixir` directory.

**Comment by bgracie** [comment]
Waiting on 1.9.1's docker release https://github.com/bitwalker/alpine-elixir-phoenix/pull/52.

We don't want to use 1.9.0 since it has formatter bugs.

**Comment by nicholasjhenry** [comment]
@bokay Even though we won't be using `1.9.0`for Giverny let's get address the feedback here and get this merged, so we can use the make tasks for our next upgrade. Thank you.

**Comment by bgracie** [comment]
> @bokay Even though we won't be using `1.9.0`for Giverny let's get address the feedback here and get this merged, so we can use the make tasks for our next upgrade. Thank you.

I think I addressed that feedback here https://github.com/civilcode/docker/pull/12/commits/690eff2333ab6d511337d5d8f5f20a26b318e8d6 but somebody else can double check

**Comment by nicholasjhenry** [comment]
Thanks, @bgracie. The doc in `README.md` needs to be moved to `elixir/README.md`:

```
## Update a version
      make upgrade VERSION=1.9.0 SUFFIX=a
```

**Comment by nicocharlery** [comment]
@nicholasjhenry what is the purpose of the `dev` directory? I see that it hasn't been updated for months. Can we simply remove it?

**Comment by nicholasjhenry** [comment]
@bokay - I would like to keep that around for now. It's a dev environment "out of the box" that I would like to revisit. I'll update the README with a "status" to clarify.

**Review by nicholasjhenry — CHANGES_REQUESTED** [review]
@bokay I tested the make task for the upgrade, but it failed:

```
make upgrade VERSION=1.8.1 SUFFIX=a
sed -i '' 's/FROM\ bitwalker\/alpine-elixir-phoenix:.*/FROM\ bitwalker\/alpine-elixir-phoenix:1.8.1/g' **/Dockerfile
sed: **/Dockerfile: No such file or directory
make: *** [update_version] Error 1
```

Something I'm missing?

**Comment by nicocharlery** [comment]
@nicholasjhenry did you run it in a folder having a Dockerfile ? 
`**/Dockerfile` is supposed to find all Dockerfiles under the tree of directories. 
Does you shell need this to be quoted ?

**Comment by nicholasjhenry** [comment]
@bokay 

```
➜  elixir git:(chore/upgrade-elixir-1.9) ls
Dockerfile.ci  Dockerfile.dev Makefile       README.md
➜  elixir git:(chore/upgrade-elixir-1.9) make upgrade VERSION=1.8.1 SUFFIX=a
sed -i '' 's/FROM\ bitwalker\/alpine-elixir-phoenix:.*/FROM\ bitwalker\/alpine-elixir-phoenix:1.8.1/g' **/Dockerfile
sed: **/Dockerfile: No such file or directory
make: *** [update_version] Error 1
➜  elixir git:(chore/upgrade-elixir-1.9)
```

Definitely running it in the directory with the `Dockerfile`s.

> Does you shell need this to be quoted ?

I'm running out standard shell setup. The only customizations I have are here:
https://github.com/nicholasjhenry/dotfiles/blob/master/shrc.local

I tried adding the quotes and running but still the get the same error.

**Comment by nicocharlery** [comment]
@nicholasjhenry The directory is missing a file named `Dockerfile` I think. 
A limitation I saw with the regex for sed is that  `**/Dockerfile.*` does not capture a file name `Dockerfile` but will find `Dockerfile.ci` for example.

**Comment by nicholasjhenry** [comment]
@bokay Unfortunately that is not working either:

```
➜  elixir git:(chore/upgrade-elixir-1.9) ✗ cp Dockerfile.dev Dockerfile
➜  elixir git:(chore/upgrade-elixir-1.9) ✗ make upgrade VERSION=1.8.1 SUFFIX=a
sed -i '' 's/FROM\ bitwalker\/alpine-elixir-phoenix:.*/FROM\ bitwalker\/alpine-elixir-phoenix:1.8.1/g' **/Dockerfile
sed: **/Dockerfile: No such file or directory
make: *** [update_version] Error 1
```

**Comment by nicocharlery** [comment]
@nicholasjhenry Does this version work better on your shell?

**Comment by nicholasjhenry** [comment]
```
➜  elixir git:(chore/upgrade-elixir-1.9) make update_version VERSION=1.8.1 SUFFIX=d
find . -name "Dockerfile*" -exec sed -i '' 's/FROM\ bitwalker\/alpine-elixir-phoenix:.*/FROM\ bitwalker\/alpine-elixir-phoenix:1.8.1/g' {} \;
➜  elixir git:(chore/upgrade-elixir-1.9) git s
On branch chore/upgrade-elixir-1.9
Your branch is up to date with 'origin/chore/upgrade-elixir-1.9'.

nothing to commit, working tree clean
```

It's not changing the version.

**Review by nicholasjhenry — APPROVED** [review]

**Pull request merged**
